did getStatistic method in WorkWithFile class
mate-academy/jv-work-with-file pull request #1226
Opened 2023-11-07 17:44 UTC by maxymmusiienko

2023-11-07 18:14 UTC, olekskov requested changes

2023-11-07 18:14 UTC, olekskov commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(fromFileName));
Please split logic into 3 separate methods
readFileContent
generateReport
writeToFile
https://github.com/mate-academy/jv-work-with-file/blob/master/checklist.md#divide-program-logic

2023-11-08 14:32 UTC, Rommelua requested changes

2023-11-08 14:32 UTC, Rommelua commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        String[] lines = fileContent.split("\n");
use lineSeparator

2023-11-08 18:56 UTC, Ivan95kos requested changes

2023-11-08 18:56 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            String[] parts = line.split(",");
All magic numbers, strings, and symbols in your code should be constants.
[this article](https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names)
```suggestion
            String[] parts = line.split(SEPARATOR);
```

2023-11-08 18:56 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        String[] lines = fileContent.split("\n");
```suggestion
        String[] lines = fileContent.split(System.lineSeparator());
```

2023-11-08 18:56 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                content.append(line).append("\n");
```suggestion
                content.append(line).append(System.lineSeparator());
```

2023-11-08 18:56 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                int amount = Integer.parseInt(parts[1]);
not fixed

2023-11-08 18:56 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            e.printStackTrace();
add the description of exception
```suggestion
            throw new RuntimeException("Can't read file: " + fileName, e);
```

2023-11-08 18:56 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                + result;
All magic numbers, strings, and symbols in your code should be constants.
[this article](https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names)

2023-11-08 18:56 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            e.printStackTrace();
add the description of exception

2023-11-09 10:15 UTC, kozhukhovsky approved these changes

2026-05-28 12:27 UTC, closed without merging