mvn complete
mate-academy/jv-work-with-file pull request #1322
Opened 2024-02-15 14:20 UTC by qreqit

2024-02-15 18:11 UTC, MentorMA requested changes

2024-02-15 18:11 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
>      }
![image](https://github.com/mate-academy/jv-work-with-file/assets/156338484/bce6fbb6-3ae9-4833-a4ab-900a29ab8ba6)

2024-02-15 18:11 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
>      }
![image](https://github.com/mate-academy/jv-work-with-file/assets/156338484/1dd29076-ecaf-4661-9f85-bdb13f88737d)

2024-02-18 10:32 UTC, MentorMA requested changes

2024-02-18 10:32 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                data.append(line).append("\n");
Use lineSeparator in thus case

2024-02-18 10:32 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            e.printStackTrace();
```suggestion
```

2024-02-18 10:32 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            e.printStackTrace();
Bad practice

2024-02-18 10:32 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        String[] lines = dataFromFile.split("\n");
The same, you can save lineSeparator to constant

2024-02-18 10:32 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            e.printStackTrace();
```suggestion
```

2024-02-18 10:32 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        return "supply," + supplyTotal + "\nbuy," + buyTotal + "\nresult," + result;
Magic numbers and strings save to constants

2024-02-18 11:58 UTC, MentorMA commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        return "supply," + supplyTotal + "\nbuy," + buyTotal + "\nresult," + result;
Not fixed

2024-02-18 12:00 UTC, MentorMA requested changes

2024-02-18 15:07 UTC, Rommelua approved these changes

2026-01-20 12:16 UTC, closed without merging