added implementation of the getStatistic method
mate-academy/jv-work-with-file pull request #1349
Opened 2024-02-22 09:31 UTC by mstefanchuk

2024-02-22 12:22 UTC, kozhukhovsky requested changes

2024-02-22 12:22 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
>      public void getStatistic(String fromFileName, String toFileName) {
https://github.com/mate-academy/jv-work-with-file/blob/master/checklist.md#divide-program-logic

Please split method logic to separate private methods (read file content, form report from file content and write report to file) and use these methods in the public one

2024-02-22 19:47 UTC, okuzan requested changes

2024-02-22 19:47 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +
move try catch finally into read, write methods
always include filename in exception messages related to files

2024-02-22 19:47 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                int amount = Integer.parseInt(parts[1]);
extract OPERTAION_INDEX constant, etc

2024-02-24 16:26 UTC, olekskov approved these changes
Good job, approved.
Please pay attention to comment below for future

2024-02-24 16:26 UTC, olekskov commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        }
You handle exceptions within private methods, no need to additionally do it in parent method
```suggestion
            String fileContent = readFileContent(fromFileName);
            String report = formReport(fileContent);
            writeReportToFile(toFileName, report);
```

2024-04-22 16:10 UTC, closed without merging