Implemented method `getStatistic(String fromFileName, String toFileName)
mate-academy/jv-work-with-file pull request #1417
Opened 2024-05-09 18:13 UTC by Jacalius

2024-05-10 05:17 UTC, Elena-Bruyako requested changes

2024-05-10 05:17 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
>      public void getStatistic(String fromFileName, String toFileName) {
[Divide program logic](https://github.com/mate-academy/jv-work-with-file/blob/master/checklist.md#divide-program-logic)
Let's create separate methods: `readFile(fromFileName); getResult(output); writeToFile(result, toFileName);`

2024-05-10 05:17 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private static final String RESULT_SUPPLY = "supply";
Pointless duplication, remove 
```
private static final String RESULT_SUPPLY = "supply";
private static final String RESULT_BUY = "buy";
```

Add constant for "comma" and all magic numbers, that you use

2024-05-10 05:17 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            bufferedWriter.write(RESULT_SUPPLY + "," + countSupply);
For creating report is better to use StringBuilder.append()

2024-05-10 05:17 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("Can't read file:", e);
Let's improve your error message see the [link](https://github.com/mate-academy/jv-work-with-file/blob/master/checklist.md#dont-ignore-exceptions)

2024-05-11 05:32 UTC, Elena-Bruyako requested changes

2024-05-11 05:32 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private static final String COMMA = ",";
create also such constants: but, supply, result

2024-05-11 05:32 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                stringBuilder.append(line).append("\n");
```suggestion
                stringBuilder.append(line).append(System.lineSeparator());
```

2024-05-11 12:13 UTC, okuzan requested changes

2024-05-11 12:13 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                int amount = Integer.parseInt(parts[1].trim());
extract to OPERATION_INDEX, AMOUNT_INDEX constants

2024-05-12 06:21 UTC, Elena-Bruyako approved these changes

2024-10-21 15:44 UTC, closed without merging