jv-work-with-file
mate-academy/jv-work-with-file pull request #1430
Opened 2024-06-05 15:32 UTC by alwayswannajava

2024-06-05 15:39 UTC, closed without merging

2024-06-05 18:27 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/WriterToFile.java
> +            bufferedWriter.write(WRITE_RESULT_STRING + FileParser.COMMA_SEPARATOR + resultValue);
it has to be extracted to separete method/service

2024-06-06 14:00 UTC, MentorMateAcademy requested changes

2024-06-06 14:00 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/ReportGenerator.java
> +    public static final String COMMA_SEPARATOR = ",";
Why this constant is public?

2024-06-06 18:31 UTC, Vasul-Pankiv approved these changes
Good Job!