add getStatistic method
mate-academy/jv-work-with-file pull request #1497
Opened 2024-09-02 18:20 UTC by skotsurskiy

2024-09-02 18:20 UTC, mateacademy-ai-mentor requested changes
Hey there! It looks like you've done a great job with the `WrongOptionException` implementation. 👍 However, there are a few areas that could be improved for better code quality and maintainability. Specifically, it's important to include the original exceptions when re-throwing to maintain the stack trace, which is crucial for debugging. Also, consider renaming variables and methods to more accurately describe their purpose, and think about adhering to the single responsibility principle by splitting methods that perform multiple tasks. These changes will make your code cleaner and easier to understand and maintain. Keep up the good work, and with a few tweaks, your code will be even better! 😊

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-09-02 18:20 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    }
This method seems to be doing multiple tasks such as calculating sums and writing to a file. Consider dividing it into separate methods to adhere to the single responsibility principle.

2024-09-02 18:20 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("Cannot write file " + e);
When re-throwing the exception, include the original exception as a cause to preserve the stack trace. Use 'throw new RuntimeException("Cannot write to file: " + toFileName, e);' instead.

2024-09-02 18:20 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private int countSupplyOrBuyInFile(String fromFileName, String option) {
The method name 'countSupplyOrBuyInFile' could be more descriptive of its purpose. Consider renaming it to reflect that it calculates the total amount of a given operation, like 'calculateTotalAmountOfOperation'.

2024-09-02 18:20 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            int supplyCounterReturn = 0;
The variable name 'supplyCounterReturn' does not accurately describe its purpose, as it counts both supply and buy operations depending on the option. Consider renaming it to 'operationSum' or a similar name that reflects its functionality.

2024-09-02 18:20 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("Cannot read file " + e);
Similar to the previous catch block, include the original exception when re-throwing to preserve the stack trace. Use 'throw new RuntimeException("Cannot read from file: " + fromFileName, e);' instead.

2024-09-03 07:01 UTC, Elena-Bruyako requested changes

2024-09-03 07:01 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        if (!option.equals(BUY_OPERATION) && !option.equals(SUPPLY_OPERATION)) {
rename option

2024-09-03 07:01 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new WrongOptionException("Wrong option");
rename exception

2024-09-03 07:01 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        try (BufferedReader input = new BufferedReader(new FileReader(fromFileName))) {
it's better to use separate readFromFile method because calculateTotalAmountOfOperation isn't responsible for this logic

2024-09-03 16:26 UTC, Sanderfuck approved these changes

2024-09-03 16:26 UTC, Sanderfuck commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        try (BufferedWriter output = new BufferedWriter(new FileWriter(toFileName))) {
Why output?

2024-09-03 16:27 UTC, MentorMateAcademy approved these changes

2024-09-03 18:04 UTC, skotsurskiy commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        try (BufferedWriter output = new BufferedWriter(new FileWriter(toFileName))) {
misprint

2025-09-27 08:06 UTC, closed without merging