getStatistic method was implemented
mate-academy/jv-work-with-file pull request #207
Opened 2021-09-17 12:34 UTC by Artem-Kushniruk

2021-09-17 14:24 UTC, RomanDubovskyi requested changes

2021-09-17 14:24 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        /* reading data from file */
давай розділио метод на дрібніші (зчитування файлу / формування ріпорту / запис готового ріпорту)

2021-09-17 14:24 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        String[] linesToWrite = {"supply," + supplyTotal, "buy," + buyTotal, "result," + result};
масив тут зайвим виглядає, можна просто строку створити і одразу без циклу її записати

2021-09-17 15:42 UTC, Artem-Kushniruk commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        /* reading data from file */
Так і думав зробити), але потім передумав, вирішив що код і так невеликий, розділений частини коментами.

2021-09-17 15:42 UTC, Artem-Kushniruk commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        String[] linesToWrite = {"supply," + supplyTotal, "buy," + buyTotal, "result," + result};
Дякую

2021-09-20 06:45 UTC, RomanDubovskyi approved these changes

2021-09-20 06:45 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                supplyTotal += Integer.parseInt(lineParts[1]);
supplyTotal можна зробити локальною змінною в цьому методі

2023-11-10 16:40 UTC, closed without merging