first try
mate-academy/jv-work-with-file pull request #661
Opened 2022-10-21 21:12 UTC by Watxesnavo

2022-10-22 10:09 UTC, zachar-chorny requested changes
Good job. But let's add constants for all the magic numbers and strings

2022-10-22 10:09 UTC, zachar-chorny commented on src/main/java/core/basesyntax/WorkWithFile.java
remove empty line

2022-10-22 10:09 UTC, zachar-chorny commented on src/main/java/core/basesyntax/WorkWithFile.java
> +
empty line

2022-10-23 15:58 UTC, Rommelua requested changes

2022-10-23 15:58 UTC, Rommelua commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("Something gone wrong to read the file");
```suggestion
            throw new RuntimeException("Something gone wrong to read the file: " + fromFileName);
```

2022-10-23 15:58 UTC, Rommelua commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("Something gone wrong to write to the file");
```suggestion
            throw new RuntimeException("Something gone wrong to write to the file: " + toFileName);
```

2022-10-23 15:58 UTC, Rommelua commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                    .append(",")
Not fixed
![image](https://user-images.githubusercontent.com/20326858/197402399-f3ed4217-38b5-49a7-a921-3ac1bba656de.png)

2022-10-25 17:34 UTC, kateryna-deshchinska requested changes
You need to create constants for all magic number and string in your code, for example :
    private static String NEW_LINE = System.lineSeparator();
    private static int OPERATION_INDEX = 0;
    private static int AMOUNT_INDEX = 1;
    and the same for other string
    
Its are class fields, not inside of methods. And after that you may use this constant inside methods.

2022-10-26 18:05 UTC, kateryna-deshchinska approved these changes

2022-10-26 18:05 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                    .append(",")
also, make constant for coma

2024-10-31 17:45 UTC, closed without merging