i add methods, BufferedWriter, BufferedReader
mate-academy/jv-work-with-file pull request #682
Opened 2022-11-11 16:22 UTC by diana-lomei

2022-11-11 16:44 UTC, aaananas requested changes
<img width="824" alt="image" src="https://user-images.githubusercontent.com/81781479/201388492-1ba2c9ba-3ca5-4017-93f5-9857adb5bfa9.png">

2022-11-11 23:29 UTC, diana-lomei commented
i fix problems with building and I rewrote the code.

2022-11-12 11:24 UTC, kozhukhovsky requested changes

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +
remove empty line

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +
remove empty line

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private int buy = 0;
```suggestion
```
make this variables local, they used only in one method

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    public String readFile(String fromFileName) {
make additional methods private

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("File not found ", e);
```suggestion
            throw new RuntimeException("File not found: " + fromFileName, e);
```

make exceptions message more informative

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        try {
you can use try with resource

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    public String calculateData(String data) {
```suggestion
    public String createReport(String data) {
```

2022-11-12 11:24 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("Somethigs was wrong.", e);
```suggestion
            throw new RuntimeException("Can't write data to file: " + toFileName, e);
```

2022-11-12 11:45 UTC, kozhukhovsky approved these changes

2025-02-21 12:02 UTC, closed without merging