jv-work-with-file
mate-academy/jv-work-with-file pull request #891
Opened 2023-03-06 14:51 UTC by VolodymyrDavidov

2023-03-06 19:53 UTC, Ivan95kos requested changes

2023-03-06 19:53 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        StringBuilder stringBuilder = new StringBuilder();
do not use such naming(stringBuilder), how to guess what it stores?

2023-03-06 19:53 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        recordToFile(result,toFileName);
```suggestion
        recordToFile(result, toFileName);
```

2023-03-06 19:53 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            throw new RuntimeException("This file cannot be read ", e);
```suggestion
            throw new RuntimeException("Can't read data from the file: " + fromFileName, e);
```

2023-03-06 19:53 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private static final String RESULT = "result";
The name of the constant should not be the same as the value being stored

2023-03-06 19:53 UTC, Ivan95kos commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        String[] dataArray = dataOfFile.split(",");
```suggestion
        String[] dataArray = dataOfFile.split(COMMA);
```

2023-03-08 10:38 UTC, okuzan requested changes

2023-03-08 10:38 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private static final String DEFAULT_SUPPLY = "supply";
why default? it denotes operation, better call it OPERATION_SUPPLY

2023-03-08 10:38 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private void recordToFile(String stringForWritingToFile, String toFileName) {
```suggestion
    private void writeToFile(String content, String toFileName) {
```
recording is for audio

2023-03-08 10:38 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private String resultOfDataReading(String dataOfFile) {
```suggestion
    private String generateReport(String fileData) {
```
method names should be verbs, save nouns for class names :)

2023-03-08 10:38 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private static final String COMA = ",";
```suggestion
    private static final String DELIMITER = ",";
```
could be SEPARATOR too
and it's `comma` just FYI

2023-03-08 10:38 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(toFileName));
https://mate-academy.github.io/jv-program-common-mistakes/java-core/builder-file/work-with-file#try-with-resources

2023-03-10 12:52 UTC, uliana-andrushchuk requested changes

2023-03-10 12:52 UTC, uliana-andrushchuk commented on src/main/java/core/basesyntax/WorkWithFile.java
> +            BufferedReader bufferedReader = new BufferedReader(new FileReader(fromFileName));
Please, use try-with-resources here
https://mate-academy.github.io/jv-program-common-mistakes/java-core/builder-file/work-with-file#try-with-resources

2023-03-10 19:42 UTC, okuzan requested changes
Generating report logic can be refactored to be less error-prone. It's better to rely on constants, to have a clear separation between lines, and not transform input into one long command line

2023-03-10 19:42 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +                dataToString.append(line).append(SEPARATOR);
```suggestion
                dataToString.append(line).append(System.lineSeparator());
```

2023-03-10 19:42 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        String[] dataArray = fileData.split(SEPARATOR);
```suggestion
        String[] dataArray = fileData.split(System.lineSeparator());
```

2023-03-10 19:42 UTC, okuzan commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        }
1. use for each
2. inside a loop, split by SEPARATOR
3. retrieve amount and operation type by indexes which are class constants

2023-03-11 12:08 UTC, closed without merging