File solution
mate-academy/jv-work-with-file pull request #908
Opened 2023-03-28 17:25 UTC by z1row

2023-03-28 18:00 UTC, olekskov requested changes
There are test failures and build is failed, please recheck fix locally and commit changes

2023-03-30 11:27 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +    private String fileToString(String fromFileName) {
```suggestion
    private String readFile(String fromFileName) {
```

2023-03-30 11:29 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        createReport(buy, supply, result, toFileName);
```suggestion
        String[] separatedItems = fileContent.split(System.lineSeparator());
        int buy = 0;
        int supply = 0;
        for (String item : separatedItems) {
            String[] splited = item.split(",");
            if (splited[0].equals("buy")) {
                buy += Integer.parseInt(splited[1]);
            } else {
                supply += Integer.parseInt(splited[1]);
            }
        }
        final int result = supply - buy;
        createReport(buy, supply, result, toFileName);
```

Move the report creation logic into a separate method

2023-03-30 11:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/WorkWithFile.java
> +        }
Checks are good, but they are not necessary for this assignment.

2023-03-31 11:02 UTC, uliana-andrushchuk approved these changes

2025-02-09 02:01 UTC, closed without merging